VSHA-267 Changes to RTS values.yaml to make RTS work on vShasta
Cray-HPE/hms-rts-charts pull request #12
Opened 2023-04-10 20:17 UTC by erl-hpe

## Summary and Scope

Restore chart settings from the distant past that make it possible to enable Google mode for RTS to allow it to work on Virtual Shasta.

This is a backward compatible change.

## Issues and Related PRs

* Relates to [VSHA-267](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-267)

## Testing

Tested on:

  * Virtual Shasta

Test description:

Deployed chart with appropriate overrides in customizations.yaml and verified that the resulting RTS came up using the Google helpers and discovered nodes. Deployed the same chart without the customizations.yaml overrides and verified that RTS came up as it has in the past on vShasta.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If not, why? n
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A

## Risks and Mitigations

There are no known risks associated with this change.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable

2023-05-18 16:11 UTC, alvarez3-hpe commented
These changes should be made to the v3.0 chart instead of the v2.0 chart

2023-05-18 16:13 UTC, alvarez3-hpe commented
You should also update `cray-hms-rts.compatibility.yaml`

2023-05-18 18:23 UTC, alvarez3-hpe requested changes
Please make these changes to the v3.0 chart instead of the v2.0 chart and `cray-hms-rts.compatibility` needs to be updated.

2023-05-22 15:45 UTC, mjendrysik-hpe approved these changes

2023-05-24 17:28 UTC, alvarez3-hpe approved these changes

2023-05-25 00:43 UTC, merged